/**
 * Dynamic security.txt Route
 *
 * Serves security.txt only when custom content is set in settings.
 * No content is generated by default.
 * See: https://www.rfc-editor.org/rfc/rfc9116
 */

import { NextResponse } from 'next/server';
import { getSettingByKey } from '@/lib/repositories/settingsRepository';

export async function GET() {
  try {
    const customSecurity = await getSettingByKey('security_txt');

    if (customSecurity && typeof customSecurity === 'string' && customSecurity.trim()) {
      return new NextResponse(customSecurity.trim(), {
        headers: {
          'Content-Type': 'text/plain; charset=utf-8',
          'Cache-Control': 'public, max-age=86400, s-maxage=86400',
        },
      });
    }

    return new NextResponse(null, { status: 404 });
  } catch (error) {
    console.error('[security.txt] Error:', error);
    return new NextResponse(null, { status: 404 });
  }
}
